package com.nuked.portal.dto;

import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class MarkAttendanceRequest {

    @NotNull
    private Long sessionId;

    /** Optional — internal session token. */
    private String sessionToken;

    /**
     * Name of the BLE peripheral the student's browser paired with. Must
     * equal the session's recorded `bleDeviceName` — otherwise the mark is
     * rejected (proves the student is within Bluetooth range of the teacher's
     * broadcaster). Normalised server-side so visually-identical strings
     * (curly vs straight quotes, casing, NBSP) compare equal.
     */
    private String bleDeviceName;

    /** Student's current lat/long. Cross-checked against the session's
     *  classroom coords; > radius meters away → rejected. */
    private Double latitude;
    private Double longitude;

    /**
     * Per-browser UUID generated by the student's device (localStorage) on
     * first portal visit. Used for per-session device binding: same UUID
     * cannot mark for two different enrollments in the same session.
     */
    private String deviceUuid;

    /**
     * Stable-across-browsers device signature (screen + language + timezone).
     * Faculty-side flag only — never used for auto-reject because two students
     * with identical phone models would collide.
     */
    private String clientFingerprint;
}
