package com.nuked.portal.dto;

import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class MarkAttendanceRequest {

    @NotNull
    private Long sessionId;

    /** Optional — internal session token. */
    private String sessionToken;

    /**
     * 6-digit PIN the teacher announced/projected when opening the session.
     * Must equal the session's recorded `pinCode` — otherwise the mark is
     * rejected. Combined with geolocation, this proves the student was in
     * the classroom when the PIN was shown.
     */
    private String pinCode;

    /** Student's current lat/long. Cross-checked against the session's
     *  classroom coords; > radius meters away → rejected. */
    private Double latitude;
    private Double longitude;

    /**
     * Per-browser UUID generated by the student's device (localStorage) on
     * first portal visit. Used for per-session device binding: same UUID
     * cannot mark for two different enrollments in the same session.
     */
    private String deviceUuid;

    /**
     * Stable-across-browsers device signature (screen + language + timezone).
     * Faculty-side flag only — never used for auto-reject because two students
     * with identical phone models would collide.
     */
    private String clientFingerprint;
}
